version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_contenedor
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    restart: always
    ports:
      - "3000:1000"
    depends_on:
      - mongo
